version: "3.8"
services:
  web:
    build:
      context: .
    image: web_upp_web:${TAG}
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
        mode: "non-blocking"
        max-buffer-size: "1m"

  loki:
    image: grafana/loki:2.9.2
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yaml

  grafana:
    image: grafana/grafana:10.0.3
    ports:
      - "3000:3000"
